/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TemplateService } from "../template.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TemplateCreateInput } from "./TemplateCreateInput";
import { TemplateWhereInput } from "./TemplateWhereInput";
import { TemplateWhereUniqueInput } from "./TemplateWhereUniqueInput";
import { TemplateFindManyArgs } from "./TemplateFindManyArgs";
import { TemplateUpdateInput } from "./TemplateUpdateInput";
import { Template } from "./Template";
import { CategoryTemplateFindManyArgs } from "../../categoryTemplate/base/CategoryTemplateFindManyArgs";
import { CategoryTemplate } from "../../categoryTemplate/base/CategoryTemplate";
import { CategoryTemplateWhereUniqueInput } from "../../categoryTemplate/base/CategoryTemplateWhereUniqueInput";
import { GroupTemplateFindManyArgs } from "../../groupTemplate/base/GroupTemplateFindManyArgs";
import { GroupTemplate } from "../../groupTemplate/base/GroupTemplate";
import { GroupTemplateWhereUniqueInput } from "../../groupTemplate/base/GroupTemplateWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TemplateControllerBase {
  constructor(
    protected readonly service: TemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Template })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: TemplateCreateInput): Promise<Template> {
    return await this.service.create({
      data: {
        ...data,

        ownerId: data.ownerId
          ? {
              connect: data.ownerId,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        ownerId: {
          select: {
            id: true,
          },
        },

        templateName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Template] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(TemplateFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Template[]> {
    const args = plainToClass(TemplateFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        ownerId: {
          select: {
            id: true,
          },
        },

        templateName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Template })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: TemplateWhereUniqueInput
  ): Promise<Template | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        ownerId: {
          select: {
            id: true,
          },
        },

        templateName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Template })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: TemplateWhereUniqueInput,
    @common.Body() data: TemplateUpdateInput
  ): Promise<Template | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          ownerId: data.ownerId
            ? {
                connect: data.ownerId,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          ownerId: {
            select: {
              id: true,
            },
          },

          templateName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Template })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: TemplateWhereUniqueInput
  ): Promise<Template | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          ownerId: {
            select: {
              id: true,
            },
          },

          templateName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CategoryTemplate",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/categoryTemplates")
  @ApiNestedQuery(CategoryTemplateFindManyArgs)
  async findManyCategoryTemplates(
    @common.Req() request: Request,
    @common.Param() params: TemplateWhereUniqueInput
  ): Promise<CategoryTemplate[]> {
    const query = plainToClass(CategoryTemplateFindManyArgs, request.query);
    const results = await this.service.findCategoryTemplates(params.id, {
      ...query,
      select: {
        categoryId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        templateId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/categoryTemplates")
  async connectCategoryTemplates(
    @common.Param() params: TemplateWhereUniqueInput,
    @common.Body() body: CategoryTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryTemplates: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/categoryTemplates")
  async updateCategoryTemplates(
    @common.Param() params: TemplateWhereUniqueInput,
    @common.Body() body: CategoryTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryTemplates: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/categoryTemplates")
  async disconnectCategoryTemplates(
    @common.Param() params: TemplateWhereUniqueInput,
    @common.Body() body: CategoryTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryTemplates: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "GroupTemplate",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/groupTemplates")
  @ApiNestedQuery(GroupTemplateFindManyArgs)
  async findManyGroupTemplates(
    @common.Req() request: Request,
    @common.Param() params: TemplateWhereUniqueInput
  ): Promise<GroupTemplate[]> {
    const query = plainToClass(GroupTemplateFindManyArgs, request.query);
    const results = await this.service.findGroupTemplates(params.id, {
      ...query,
      select: {
        createdAt: true,

        groupId: {
          select: {
            id: true,
          },
        },

        id: true,

        templateId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/groupTemplates")
  async connectGroupTemplates(
    @common.Param() params: TemplateWhereUniqueInput,
    @common.Body() body: GroupTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      groupTemplates: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/groupTemplates")
  async updateGroupTemplates(
    @common.Param() params: TemplateWhereUniqueInput,
    @common.Body() body: GroupTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      groupTemplates: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/groupTemplates")
  async disconnectGroupTemplates(
    @common.Param() params: TemplateWhereUniqueInput,
    @common.Body() body: GroupTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      groupTemplates: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
