/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FileViewSettingService } from "../fileViewSetting.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FileViewSettingCreateInput } from "./FileViewSettingCreateInput";
import { FileViewSettingWhereInput } from "./FileViewSettingWhereInput";
import { FileViewSettingWhereUniqueInput } from "./FileViewSettingWhereUniqueInput";
import { FileViewSettingFindManyArgs } from "./FileViewSettingFindManyArgs";
import { FileViewSettingUpdateInput } from "./FileViewSettingUpdateInput";
import { FileViewSetting } from "./FileViewSetting";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FileViewSettingControllerBase {
  constructor(
    protected readonly service: FileViewSettingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FileViewSetting",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FileViewSetting })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: FileViewSettingCreateInput
  ): Promise<FileViewSetting> {
    return await this.service.create({
      data: {
        ...data,

        generalSettingId: data.generalSettingId
          ? {
              connect: data.generalSettingId,
            }
          : undefined,

        identity: data.identity
          ? {
              connect: data.identity,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        generalSettingId: {
          select: {
            id: true,
          },
        },

        id: true,

        identity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FileViewSetting",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [FileViewSetting] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(FileViewSettingFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<FileViewSetting[]> {
    const args = plainToClass(FileViewSettingFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        generalSettingId: {
          select: {
            id: true,
          },
        },

        id: true,

        identity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FileViewSetting",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FileViewSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: FileViewSettingWhereUniqueInput
  ): Promise<FileViewSetting | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        generalSettingId: {
          select: {
            id: true,
          },
        },

        id: true,

        identity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FileViewSetting",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FileViewSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: FileViewSettingWhereUniqueInput,
    @common.Body() data: FileViewSettingUpdateInput
  ): Promise<FileViewSetting | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          generalSettingId: data.generalSettingId
            ? {
                connect: data.generalSettingId,
              }
            : undefined,

          identity: data.identity
            ? {
                connect: data.identity,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          generalSettingId: {
            select: {
              id: true,
            },
          },

          id: true,

          identity: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "FileViewSetting",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FileViewSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: FileViewSettingWhereUniqueInput
  ): Promise<FileViewSetting | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          generalSettingId: {
            select: {
              id: true,
            },
          },

          id: true,

          identity: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
