/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Category } from "../../category/base/Category";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsBoolean,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { FileView } from "../../fileView/base/FileView";
import { HashtagFile } from "../../hashtagFile/base/HashtagFile";
import { User } from "../../user/base/User";
import { PermissionGroup } from "../../permissionGroup/base/PermissionGroup";
import { RequestDatum } from "../../requestDatum/base/RequestDatum";
@ObjectType()
class FileDatum {
  @ApiProperty({
    required: false,
    type: () => Category,
  })
  @ValidateNested()
  @Type(() => Category)
  @IsOptional()
  cateogyId?: Category | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  deleted!: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  file!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fileType!: string | null;

  @ApiProperty({
    required: false,
    type: () => [FileView],
  })
  @ValidateNested()
  @Type(() => FileView)
  @IsOptional()
  fileViews?: Array<FileView>;

  @ApiProperty({
    required: false,
    type: () => [HashtagFile],
  })
  @ValidateNested()
  @Type(() => HashtagFile)
  @IsOptional()
  hashtagFiles?: Array<HashtagFile>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isFile!: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isGallery!: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPublic!: boolean | null;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  ownerId?: User | null;

  @ApiProperty({
    required: false,
    type: () => PermissionGroup,
  })
  @ValidateNested()
  @Type(() => PermissionGroup)
  @IsOptional()
  permissionId?: PermissionGroup | null;

  @ApiProperty({
    required: false,
    type: () => [RequestDatum],
  })
  @ValidateNested()
  @Type(() => RequestDatum)
  @IsOptional()
  requestData?: Array<RequestDatum>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { FileDatum };
