/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PermissionContactService } from "../permissionContact.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PermissionContactCreateInput } from "./PermissionContactCreateInput";
import { PermissionContactWhereInput } from "./PermissionContactWhereInput";
import { PermissionContactWhereUniqueInput } from "./PermissionContactWhereUniqueInput";
import { PermissionContactFindManyArgs } from "./PermissionContactFindManyArgs";
import { PermissionContactUpdateInput } from "./PermissionContactUpdateInput";
import { PermissionContact } from "./PermissionContact";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PermissionContactControllerBase {
  constructor(
    protected readonly service: PermissionContactService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PermissionContact",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PermissionContact })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PermissionContactCreateInput
  ): Promise<PermissionContact> {
    return await this.service.create({
      data: {
        ...data,

        contactRelationId: data.contactRelationId
          ? {
              connect: data.contactRelationId,
            }
          : undefined,
      },
      select: {
        contactRelationId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        files: true,
        gallery: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PermissionContact",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [PermissionContact] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PermissionContactFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<PermissionContact[]> {
    const args = plainToClass(PermissionContactFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        contactRelationId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        files: true,
        gallery: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PermissionContact",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PermissionContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PermissionContactWhereUniqueInput
  ): Promise<PermissionContact | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        contactRelationId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        files: true,
        gallery: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PermissionContact",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PermissionContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PermissionContactWhereUniqueInput,
    @common.Body() data: PermissionContactUpdateInput
  ): Promise<PermissionContact | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          contactRelationId: data.contactRelationId
            ? {
                connect: data.contactRelationId,
              }
            : undefined,
        },
        select: {
          contactRelationId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          files: true,
          gallery: true,
          id: true,
          location: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "PermissionContact",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PermissionContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PermissionContactWhereUniqueInput
  ): Promise<PermissionContact | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          contactRelationId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          files: true,
          gallery: true,
          id: true,
          location: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
