/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { CategoryTemplateListRelationFilter } from "../../categoryTemplate/base/CategoryTemplateListRelationFilter";
import { FileDatumListRelationFilter } from "../../fileDatum/base/FileDatumListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { LinkDatumListRelationFilter } from "../../linkDatum/base/LinkDatumListRelationFilter";
import { ProfileListRelationFilter } from "../../profile/base/ProfileListRelationFilter";
import { RequestDatumListRelationFilter } from "../../requestDatum/base/RequestDatumListRelationFilter";
import { SuggestionDatumListRelationFilter } from "../../suggestionDatum/base/SuggestionDatumListRelationFilter";
@InputType()
class CategoryWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  categoryName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CategoryTemplateListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CategoryTemplateListRelationFilter)
  @IsOptional()
  @Field(() => CategoryTemplateListRelationFilter, {
    nullable: true,
  })
  categoryTemplates?: CategoryTemplateListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FileDatumListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FileDatumListRelationFilter)
  @IsOptional()
  @Field(() => FileDatumListRelationFilter, {
    nullable: true,
  })
  fileData?: FileDatumListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LinkDatumListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LinkDatumListRelationFilter)
  @IsOptional()
  @Field(() => LinkDatumListRelationFilter, {
    nullable: true,
  })
  linkData?: LinkDatumListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ProfileListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProfileListRelationFilter)
  @IsOptional()
  @Field(() => ProfileListRelationFilter, {
    nullable: true,
  })
  profiles?: ProfileListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RequestDatumListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RequestDatumListRelationFilter)
  @IsOptional()
  @Field(() => RequestDatumListRelationFilter, {
    nullable: true,
  })
  requestData?: RequestDatumListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SuggestionDatumListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SuggestionDatumListRelationFilter)
  @IsOptional()
  @Field(() => SuggestionDatumListRelationFilter, {
    nullable: true,
  })
  suggestionData?: SuggestionDatumListRelationFilter;
}
export { CategoryWhereInput };
