/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsDate } from "class-validator";
import { CategoryTemplate } from "../../categoryTemplate/base/CategoryTemplate";
import { Type } from "class-transformer";
import { FileDatum } from "../../fileDatum/base/FileDatum";
import { LinkDatum } from "../../linkDatum/base/LinkDatum";
import { Profile } from "../../profile/base/Profile";
import { RequestDatum } from "../../requestDatum/base/RequestDatum";
import { SuggestionDatum } from "../../suggestionDatum/base/SuggestionDatum";
@ObjectType()
class Category {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoryName!: string | null;

  @ApiProperty({
    required: false,
    type: () => [CategoryTemplate],
  })
  @ValidateNested()
  @Type(() => CategoryTemplate)
  @IsOptional()
  categoryTemplates?: Array<CategoryTemplate>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [FileDatum],
  })
  @ValidateNested()
  @Type(() => FileDatum)
  @IsOptional()
  fileData?: Array<FileDatum>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [LinkDatum],
  })
  @ValidateNested()
  @Type(() => LinkDatum)
  @IsOptional()
  linkData?: Array<LinkDatum>;

  @ApiProperty({
    required: false,
    type: () => [Profile],
  })
  @ValidateNested()
  @Type(() => Profile)
  @IsOptional()
  profiles?: Array<Profile>;

  @ApiProperty({
    required: false,
    type: () => [RequestDatum],
  })
  @ValidateNested()
  @Type(() => RequestDatum)
  @IsOptional()
  requestData?: Array<RequestDatum>;

  @ApiProperty({
    required: false,
    type: () => [SuggestionDatum],
  })
  @ValidateNested()
  @Type(() => SuggestionDatum)
  @IsOptional()
  suggestionData?: Array<SuggestionDatum>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { Category };
