/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { CategoryTemplateUpdateManyWithoutCategoriesInput } from "./CategoryTemplateUpdateManyWithoutCategoriesInput";
import { Type } from "class-transformer";
import { FileDatumUpdateManyWithoutCategoriesInput } from "./FileDatumUpdateManyWithoutCategoriesInput";
import { LinkDatumUpdateManyWithoutCategoriesInput } from "./LinkDatumUpdateManyWithoutCategoriesInput";
import { ProfileUpdateManyWithoutCategoriesInput } from "./ProfileUpdateManyWithoutCategoriesInput";
import { RequestDatumUpdateManyWithoutCategoriesInput } from "./RequestDatumUpdateManyWithoutCategoriesInput";
import { SuggestionDatumUpdateManyWithoutCategoriesInput } from "./SuggestionDatumUpdateManyWithoutCategoriesInput";
@InputType()
class CategoryUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoryName?: string | null;

  @ApiProperty({
    required: false,
    type: () => CategoryTemplateUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => CategoryTemplateUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => CategoryTemplateUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  categoryTemplates?: CategoryTemplateUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => FileDatumUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => FileDatumUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => FileDatumUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  fileData?: FileDatumUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => LinkDatumUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => LinkDatumUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => LinkDatumUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  linkData?: LinkDatumUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => ProfileUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => ProfileUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => ProfileUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  profiles?: ProfileUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => RequestDatumUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => RequestDatumUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => RequestDatumUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  requestData?: RequestDatumUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => SuggestionDatumUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => SuggestionDatumUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => SuggestionDatumUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  suggestionData?: SuggestionDatumUpdateManyWithoutCategoriesInput;
}
export { CategoryUpdateInput };
