/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PermissionGroupNameService } from "../permissionGroupName.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PermissionGroupNameCreateInput } from "./PermissionGroupNameCreateInput";
import { PermissionGroupNameWhereInput } from "./PermissionGroupNameWhereInput";
import { PermissionGroupNameWhereUniqueInput } from "./PermissionGroupNameWhereUniqueInput";
import { PermissionGroupNameFindManyArgs } from "./PermissionGroupNameFindManyArgs";
import { PermissionGroupNameUpdateInput } from "./PermissionGroupNameUpdateInput";
import { PermissionGroupName } from "./PermissionGroupName";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PermissionGroupNameControllerBase {
  constructor(
    protected readonly service: PermissionGroupNameService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PermissionGroupName",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PermissionGroupName })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PermissionGroupNameCreateInput
  ): Promise<PermissionGroupName> {
    return await this.service.create({
      data: {
        ...data,

        identityId: data.identityId
          ? {
              connect: data.identityId,
            }
          : undefined,

        permissionGroupId: data.permissionGroupId
          ? {
              connect: data.permissionGroupId,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        groupName: true,
        id: true,

        identityId: {
          select: {
            id: true,
          },
        },

        permissionGroupId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PermissionGroupName",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [PermissionGroupName] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PermissionGroupNameFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<PermissionGroupName[]> {
    const args = plainToClass(PermissionGroupNameFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        groupName: true,
        id: true,

        identityId: {
          select: {
            id: true,
          },
        },

        permissionGroupId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PermissionGroupName",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PermissionGroupName })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PermissionGroupNameWhereUniqueInput
  ): Promise<PermissionGroupName | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        groupName: true,
        id: true,

        identityId: {
          select: {
            id: true,
          },
        },

        permissionGroupId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PermissionGroupName",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PermissionGroupName })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PermissionGroupNameWhereUniqueInput,
    @common.Body() data: PermissionGroupNameUpdateInput
  ): Promise<PermissionGroupName | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          identityId: data.identityId
            ? {
                connect: data.identityId,
              }
            : undefined,

          permissionGroupId: data.permissionGroupId
            ? {
                connect: data.permissionGroupId,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          groupName: true,
          id: true,

          identityId: {
            select: {
              id: true,
            },
          },

          permissionGroupId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "PermissionGroupName",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PermissionGroupName })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PermissionGroupNameWhereUniqueInput
  ): Promise<PermissionGroupName | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          groupName: true,
          id: true,

          identityId: {
            select: {
              id: true,
            },
          },

          permissionGroupId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
