/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ContactUpdateManyWithoutPermissionGroupsInput } from "./ContactUpdateManyWithoutPermissionGroupsInput";
import {
  ValidateNested,
  IsOptional,
  IsBoolean,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { FileDatumUpdateManyWithoutPermissionGroupsInput } from "./FileDatumUpdateManyWithoutPermissionGroupsInput";
import { PermissionGroupNameUpdateManyWithoutPermissionGroupsInput } from "./PermissionGroupNameUpdateManyWithoutPermissionGroupsInput";
@InputType()
class PermissionGroupUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ContactUpdateManyWithoutPermissionGroupsInput,
  })
  @ValidateNested()
  @Type(() => ContactUpdateManyWithoutPermissionGroupsInput)
  @IsOptional()
  @Field(() => ContactUpdateManyWithoutPermissionGroupsInput, {
    nullable: true,
  })
  contacts?: ContactUpdateManyWithoutPermissionGroupsInput;

  @ApiProperty({
    required: false,
    type: () => FileDatumUpdateManyWithoutPermissionGroupsInput,
  })
  @ValidateNested()
  @Type(() => FileDatumUpdateManyWithoutPermissionGroupsInput)
  @IsOptional()
  @Field(() => FileDatumUpdateManyWithoutPermissionGroupsInput, {
    nullable: true,
  })
  fileData?: FileDatumUpdateManyWithoutPermissionGroupsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  files?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  gallery?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  groupName?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  location?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => PermissionGroupNameUpdateManyWithoutPermissionGroupsInput,
  })
  @ValidateNested()
  @Type(() => PermissionGroupNameUpdateManyWithoutPermissionGroupsInput)
  @IsOptional()
  @Field(() => PermissionGroupNameUpdateManyWithoutPermissionGroupsInput, {
    nullable: true,
  })
  permissionGroupNames?: PermissionGroupNameUpdateManyWithoutPermissionGroupsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  status?: boolean | null;
}
export { PermissionGroupUpdateInput };
