import { Audit } from "../audit/Audit";
import { Contact } from "../contact/Contact";
import { FileDatum } from "../fileDatum/FileDatum";
import { FileViewSetting } from "../fileViewSetting/FileViewSetting";
import { FileView } from "../fileView/FileView";
import { GroupMember } from "../groupMember/GroupMember";
import { Group } from "../group/Group";
import { Hashtag } from "../hashtag/Hashtag";
import { EnumUserBlock } from "../enumUserBlock/EnumUserBlock";
import { LinkDatum } from "../linkDatum/LinkDatum";
import { NetworkPost } from "../networkPost/NetworkPost";
import { PermissionGroupName } from "../permissionGroupName/PermissionGroupName";
import { Profile } from "../profile/Profile";
import { RequestDatum } from "../requestDatum/RequestDatum";
import { ShareIdentity } from "../shareIdentity/ShareIdentity";
import { SharingUnregisteredUser } from "../sharingUnregisteredUser/SharingUnregisteredUser";
import { SuggestionDatum } from "../suggestionDatum/SuggestionDatum";
import { Template } from "../template/Template";
import { UserFcm } from "../userFcm/UserFcm";
import { UserLocation } from "../userLocation/UserLocation";

export type User = {
  audits?: Array<Audit>;
  contactsContactId?: Array<Contact>;
  contactsIdentityId?: Array<Contact>;
  country: string | null;
  createdAt: Date;
  email: string | null;
  fileData?: Array<FileDatum>;
  fileViewSettings?: Array<FileViewSetting>;
  fileViews_identity?: Array<FileView>;
  fileViews_watchId?: Array<FileView>;
  firstName: string | null;
  groupMembers?: Array<GroupMember>;
  groups?: Array<Group>;
  hashtags?: Array<Hashtag>;
  id: string;
  isActive: boolean | null;
  isBlock?: EnumUserBlock | null;
  isRegistered: boolean | null;
  keyReadFirebase: string | null;
  lastName: string | null;
  linkData?: Array<LinkDatum>;
  networkPosts?: Array<NetworkPost>;
  permissionGroupNames?: Array<PermissionGroupName>;
  phone: string;
  profiles?: Array<Profile>;
  requestDataAdkId_adkId?: Array<RequestDatum>;
  requestDataRecipientId?: Array<RequestDatum>;
  roles: Array<string>;
  shareIdentities?: Array<ShareIdentity>;
  sharingUnregisteredUsers?: Array<SharingUnregisteredUser>;
  suggestionData_recipientId?: Array<SuggestionDatum>;
  suggestionData_suggestionId?: Array<SuggestionDatum>;
  templates?: Array<Template>;
  updatedAt: Date;
  userFcms?: Array<UserFcm>;
  userLocations?: Array<UserLocation>;
  username: string;
};
