import { AuditUpdateManyWithoutUsersInput } from "./AuditUpdateManyWithoutUsersInput";
import { ContactUpdateManyWithoutUsersInput } from "./ContactUpdateManyWithoutUsersInput";
import { FileDatumUpdateManyWithoutUsersInput } from "./FileDatumUpdateManyWithoutUsersInput";
import { FileViewSettingUpdateManyWithoutUsersInput } from "./FileViewSettingUpdateManyWithoutUsersInput";
import { FileViewUpdateManyWithoutUsersInput } from "./FileViewUpdateManyWithoutUsersInput";
import { GroupMemberUpdateManyWithoutUsersInput } from "./GroupMemberUpdateManyWithoutUsersInput";
import { GroupUpdateManyWithoutUsersInput } from "./GroupUpdateManyWithoutUsersInput";
import { HashtagUpdateManyWithoutUsersInput } from "./HashtagUpdateManyWithoutUsersInput";
import { EnumUserBlockWhereUniqueInput } from "../enumUserBlock/EnumUserBlockWhereUniqueInput";
import { LinkDatumUpdateManyWithoutUsersInput } from "./LinkDatumUpdateManyWithoutUsersInput";
import { NetworkPostUpdateManyWithoutUsersInput } from "./NetworkPostUpdateManyWithoutUsersInput";
import { PermissionGroupNameUpdateManyWithoutUsersInput } from "./PermissionGroupNameUpdateManyWithoutUsersInput";
import { ProfileUpdateManyWithoutUsersInput } from "./ProfileUpdateManyWithoutUsersInput";
import { RequestDatumUpdateManyWithoutUsersInput } from "./RequestDatumUpdateManyWithoutUsersInput";
import { ShareIdentityUpdateManyWithoutUsersInput } from "./ShareIdentityUpdateManyWithoutUsersInput";
import { SharingUnregisteredUserUpdateManyWithoutUsersInput } from "./SharingUnregisteredUserUpdateManyWithoutUsersInput";
import { SuggestionDatumUpdateManyWithoutUsersInput } from "./SuggestionDatumUpdateManyWithoutUsersInput";
import { TemplateUpdateManyWithoutUsersInput } from "./TemplateUpdateManyWithoutUsersInput";
import { UserFcmUpdateManyWithoutUsersInput } from "./UserFcmUpdateManyWithoutUsersInput";
import { UserLocationUpdateManyWithoutUsersInput } from "./UserLocationUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  audits?: AuditUpdateManyWithoutUsersInput;
  contactsContactId?: ContactUpdateManyWithoutUsersInput;
  contactsIdentityId?: ContactUpdateManyWithoutUsersInput;
  country?: string | null;
  email?: string | null;
  fileData?: FileDatumUpdateManyWithoutUsersInput;
  fileViewSettings?: FileViewSettingUpdateManyWithoutUsersInput;
  fileViews_identity?: FileViewUpdateManyWithoutUsersInput;
  fileViews_watchId?: FileViewUpdateManyWithoutUsersInput;
  firstName?: string | null;
  groupMembers?: GroupMemberUpdateManyWithoutUsersInput;
  groups?: GroupUpdateManyWithoutUsersInput;
  hashtags?: HashtagUpdateManyWithoutUsersInput;
  isActive?: boolean | null;
  isBlock?: EnumUserBlockWhereUniqueInput | null;
  isRegistered?: boolean | null;
  keyReadFirebase?: string | null;
  lastName?: string | null;
  linkData?: LinkDatumUpdateManyWithoutUsersInput;
  networkPosts?: NetworkPostUpdateManyWithoutUsersInput;
  password?: string;
  permissionGroupNames?: PermissionGroupNameUpdateManyWithoutUsersInput;
  phone?: string;
  profiles?: ProfileUpdateManyWithoutUsersInput;
  requestDataAdkId_adkId?: RequestDatumUpdateManyWithoutUsersInput;
  requestDataRecipientId?: RequestDatumUpdateManyWithoutUsersInput;
  roles?: Array<string>;
  shareIdentities?: ShareIdentityUpdateManyWithoutUsersInput;
  sharingUnregisteredUsers?: SharingUnregisteredUserUpdateManyWithoutUsersInput;
  suggestionData_recipientId?: SuggestionDatumUpdateManyWithoutUsersInput;
  suggestionData_suggestionId?: SuggestionDatumUpdateManyWithoutUsersInput;
  templates?: TemplateUpdateManyWithoutUsersInput;
  userFcms?: UserFcmUpdateManyWithoutUsersInput;
  userLocations?: UserLocationUpdateManyWithoutUsersInput;
  username?: string;
};
