/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { GroupMemberUpdateManyWithoutGroupsInput } from "./GroupMemberUpdateManyWithoutGroupsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { GroupTemplateUpdateManyWithoutGroupsInput } from "./GroupTemplateUpdateManyWithoutGroupsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@InputType()
class GroupUpdateInput {
  @ApiProperty({
    required: false,
    type: () => GroupMemberUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupMemberUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupMemberUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  groupMembers?: GroupMemberUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  groupname?: string | null;

  @ApiProperty({
    required: false,
    type: () => GroupTemplateUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupTemplateUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupTemplateUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  groupTemplates?: GroupTemplateUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isDefaultGroup?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  ownerId?: UserWhereUniqueInput | null;
}
export { GroupUpdateInput };
