/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AuditService } from "../audit.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AuditCreateInput } from "./AuditCreateInput";
import { AuditWhereInput } from "./AuditWhereInput";
import { AuditWhereUniqueInput } from "./AuditWhereUniqueInput";
import { AuditFindManyArgs } from "./AuditFindManyArgs";
import { AuditUpdateInput } from "./AuditUpdateInput";
import { Audit } from "./Audit";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AuditControllerBase {
  constructor(
    protected readonly service: AuditService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Audit",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Audit })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: AuditCreateInput): Promise<Audit> {
    return await this.service.create({
      data: {
        ...data,

        userId: data.userId
          ? {
              connect: data.userId,
            }
          : undefined,
      },
      select: {
        additionalInfo: true,
        clientIp: true,
        createdAt: true,
        id: true,
        reqFullUrl: true,
        reqMethod: true,
        reqUrl: true,
        resCode: true,
        resMessage: true,
        title: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },

        userName: true,
        userType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Audit",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Audit] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(AuditFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Audit[]> {
    const args = plainToClass(AuditFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        additionalInfo: true,
        clientIp: true,
        createdAt: true,
        id: true,
        reqFullUrl: true,
        reqMethod: true,
        reqUrl: true,
        resCode: true,
        resMessage: true,
        title: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },

        userName: true,
        userType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Audit",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Audit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: AuditWhereUniqueInput
  ): Promise<Audit | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        additionalInfo: true,
        clientIp: true,
        createdAt: true,
        id: true,
        reqFullUrl: true,
        reqMethod: true,
        reqUrl: true,
        resCode: true,
        resMessage: true,
        title: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },

        userName: true,
        userType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Audit",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Audit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: AuditWhereUniqueInput,
    @common.Body() data: AuditUpdateInput
  ): Promise<Audit | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          userId: data.userId
            ? {
                connect: data.userId,
              }
            : undefined,
        },
        select: {
          additionalInfo: true,
          clientIp: true,
          createdAt: true,
          id: true,
          reqFullUrl: true,
          reqMethod: true,
          reqUrl: true,
          resCode: true,
          resMessage: true,
          title: true,
          updatedAt: true,

          userId: {
            select: {
              id: true,
            },
          },

          userName: true,
          userType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Audit",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Audit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: AuditWhereUniqueInput
  ): Promise<Audit | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          additionalInfo: true,
          clientIp: true,
          createdAt: true,
          id: true,
          reqFullUrl: true,
          reqMethod: true,
          reqUrl: true,
          resCode: true,
          resMessage: true,
          title: true,
          updatedAt: true,

          userId: {
            select: {
              id: true,
            },
          },

          userName: true,
          userType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
