/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GroupTemplateService } from "../groupTemplate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GroupTemplateCreateInput } from "./GroupTemplateCreateInput";
import { GroupTemplateWhereInput } from "./GroupTemplateWhereInput";
import { GroupTemplateWhereUniqueInput } from "./GroupTemplateWhereUniqueInput";
import { GroupTemplateFindManyArgs } from "./GroupTemplateFindManyArgs";
import { GroupTemplateUpdateInput } from "./GroupTemplateUpdateInput";
import { GroupTemplate } from "./GroupTemplate";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GroupTemplateControllerBase {
  constructor(
    protected readonly service: GroupTemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "GroupTemplate",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GroupTemplate })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: GroupTemplateCreateInput
  ): Promise<GroupTemplate> {
    return await this.service.create({
      data: {
        ...data,

        groupId: data.groupId
          ? {
              connect: data.groupId,
            }
          : undefined,

        templateId: data.templateId
          ? {
              connect: data.templateId,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        groupId: {
          select: {
            id: true,
          },
        },

        id: true,

        templateId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "GroupTemplate",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [GroupTemplate] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(GroupTemplateFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<GroupTemplate[]> {
    const args = plainToClass(GroupTemplateFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        groupId: {
          select: {
            id: true,
          },
        },

        id: true,

        templateId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "GroupTemplate",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GroupTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: GroupTemplateWhereUniqueInput
  ): Promise<GroupTemplate | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        groupId: {
          select: {
            id: true,
          },
        },

        id: true,

        templateId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "GroupTemplate",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GroupTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: GroupTemplateWhereUniqueInput,
    @common.Body() data: GroupTemplateUpdateInput
  ): Promise<GroupTemplate | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          groupId: data.groupId
            ? {
                connect: data.groupId,
              }
            : undefined,

          templateId: data.templateId
            ? {
                connect: data.templateId,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          groupId: {
            select: {
              id: true,
            },
          },

          id: true,

          templateId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "GroupTemplate",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GroupTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: GroupTemplateWhereUniqueInput
  ): Promise<GroupTemplate | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          groupId: {
            select: {
              id: true,
            },
          },

          id: true,

          templateId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
