/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FileViewService } from "../fileView.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FileViewCreateInput } from "./FileViewCreateInput";
import { FileViewWhereInput } from "./FileViewWhereInput";
import { FileViewWhereUniqueInput } from "./FileViewWhereUniqueInput";
import { FileViewFindManyArgs } from "./FileViewFindManyArgs";
import { FileViewUpdateInput } from "./FileViewUpdateInput";
import { FileView } from "./FileView";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FileViewControllerBase {
  constructor(
    protected readonly service: FileViewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FileView",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FileView })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: FileViewCreateInput): Promise<FileView> {
    return await this.service.create({
      data: {
        ...data,

        fileId: data.fileId
          ? {
              connect: data.fileId,
            }
          : undefined,

        identity: data.identity
          ? {
              connect: data.identity,
            }
          : undefined,

        watchId: data.watchId
          ? {
              connect: data.watchId,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        fileId: {
          select: {
            id: true,
          },
        },

        id: true,

        identity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        watchId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FileView",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [FileView] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(FileViewFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<FileView[]> {
    const args = plainToClass(FileViewFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        fileId: {
          select: {
            id: true,
          },
        },

        id: true,

        identity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        watchId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FileView",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FileView })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: FileViewWhereUniqueInput
  ): Promise<FileView | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        fileId: {
          select: {
            id: true,
          },
        },

        id: true,

        identity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        watchId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FileView",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FileView })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: FileViewWhereUniqueInput,
    @common.Body() data: FileViewUpdateInput
  ): Promise<FileView | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          fileId: data.fileId
            ? {
                connect: data.fileId,
              }
            : undefined,

          identity: data.identity
            ? {
                connect: data.identity,
              }
            : undefined,

          watchId: data.watchId
            ? {
                connect: data.watchId,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          fileId: {
            select: {
              id: true,
            },
          },

          id: true,

          identity: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          watchId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "FileView",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FileView })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: FileViewWhereUniqueInput
  ): Promise<FileView | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          fileId: {
            select: {
              id: true,
            },
          },

          id: true,

          identity: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          watchId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
